[font]
size = 12.0

[font.bold]
family = "0xProtoNerdFont"
style = "Bold"

[font.bold_italic]
family = "0xProtoNerdFont"
style = "Bold Italic"

[font.italic]
family = "0xProtoNerdFont"
style = "Italic"

[font.normal]
family = "0xProtoNerdFont"
style = "Regular"
